<?php session_start();?>
<!DOCTYPE html>
<html >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="webapp15" content="width=device-width, initial-scale=1.0">
<title>Trackmify-IWH'15</title>
<link rel="stylesheet" type="text/css" href="style.css"/>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,200,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800,600,300,200' rel='stylesheet' type='text/css'>
<link href="css/font-awesome.min.css" rel="stylesheet" media="screen">
<link href="css/responsive.css" rel="stylesheet" media="screen" type="text/css"/>
<link rel="stylesheet" href="sidr/stylesheets/jquery.sidr.dark.css">
<script src="js/jquery.min.js"></script>
<script src="sidr/jquery.sidr.min.js"></script>
<script type="text/javascript" src="js/smoothscroll.js"></script>
</head>



<style>
header {
	top:0px;

	position:fixed;

	width:100%;
	 background-color:white;

	padding: 0 10px 0 20px;
	height: 90px;
	margin: 0px;
	padding: 10px;
	color: #339933;

	letter-spacing:2px;
	}

</style>

<body>

<header>
    <h1 style="font-size:70px"><i><b>TAskmAniA</b></i> </h1>



<h2 style="font-size:20px; color:white; text-align:center; padding:5px;word-spacing:10px;">

<a href="home.phtml" style="color:#339933;  " target="">Home</a>     <a href="about_us.phtml" style="color:#339933;  "  target="">About Us</a>    <a href="help.phtml" style="color:#339933;  "target="_blank">Help</a>     <a href="logout.php"  style="color:#339933 "  target ="" >Logout </a>

</h2 >

</header>
   <div class="color-border">
    </div>
<div class="banner2">
        <div class="container">
            <div class="header-text">
            <div class="features-section">
            <h1>ABOUT US</h1>
            <br>
            <h3>Taskmania is an application to track your long term goals and to see how well you have performed. So shrug off that lazyness and get started</h3>
            <br>
            <br>

               <p> Taskmania is designed for the deterministic and vivacious people who love to live a life of discipline.Taskmania is a application which take care of all the goals,tasks,works,project,submission,assignment,self study and many such loads which need proper management and timeline completion .
               </p>
               <br><br>
              <p>
              Taskmania sets out time,pririoty and both time and pririoty based analysis.It showcases user's daily ,monthly or yearly performance as per her demand in the form of graphs and charts.One can set out whole bunch of tasks and many such bunches which need to be completed within times periphery. It analyses your performance periodically and dynamically gives the ultimate result of your performance.
              </p>
              <br><br>
              <p>
              Taskmania can be very helpful to the students who set out preparation for the exam and many such goals,to the employer who want check out his performance rate,to the manager who wants to check out performance of enterpise and an individual who wants to set number of goals for completion.
              </p>
              <br><br>
            <p>
            Taskmania is flexible web application which gives you many options and choices to  plan your tasks according to your comfort.Its a boon to a person and helps her to focus only on the task and rest all headache is healed by it. You need a passion to finish work and rest Taskmania will do.<br>
            </p>
            <br>
            <br><br>
            <br><br>

            </div>
        </div>
    </div>
    <div class="color-border">
    </div>

    <div class="footer">
            <div class="container">
                <div class="infooter">
                <p class="copyright">SOURCE CODE</p>
                </div>
            <ul class="socialmedia">
                <li><a href="https://github.com/sara-02/IWH-15"><i class="icon-github"></i></a></li>
            </ul>
            </div>
        </div>
</body>
</html>
