<?php session_start();?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>IWH'15</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="style.css"/>

     <link href="../css/font-awesome.min.css" rel="stylesheet" media="screen">
     <link href="../css/responsive.css" rel="stylesheet" media="screen" type="text/css"/>
    <link rel="stylesheet" href="../sidr/stylesheets/jquery.sidr.dark.css">
        <script src="../js/jquery.min.js"></script>
        <script src="../sidr/jquery.sidr.min.js"></script>
        <script type="text/javascript" src="../js/smoothscroll.js"></script>
    <!-- Bootstrap Core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="../bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="../bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<style>
header {
    top:0px;

    position:fixed;

    width:100%;
     background-color:white;

    padding: 0 10px 0 20px;
    height: 90px;
    margin: 0px;
    padding: 10px;
    color: #339933;

    letter-spacing:2px;
    }

</style>

<body>

<header>
    <h1 style="font-size:70px"><i><b>TAskmAniA</b></i> </h1>



<h2 style="font-size:20px; color:white; text-align:center; padding:5px;word-spacing:10px;">

<a href="home.phtml" style="color:#339933;  " target="">Home</a>     <a href="about_us.phtml" style="color:#339933;  "  target="">About Us</a>    <a href="help.phtml" style="color:#339933;  "target="_blank">Help</a>     <a href="logout.php"  style="color:#339933 "  target ="" >Logout </a>

</h2 >

</header>

    <div id="wrapper">



        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">NEW TASK</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" action="newtask.php" method="POST">
                                        <div class="form-group">
                                            <label>Task Set Name</label>
                                            <input class="form-control" name="group_nm" type="text"placeholder="Enter task-set name" autofocus required>
                                        </div>
                                          <div class="form-group">
                                            <label>Type of Analysis</label>
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" name="options" id="optionsRadios1" value="1" >Priority Based
                                                </label>
                                            </div>
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" name="options" id="optionsRadios2" value="2" checked>Time Based
                                                </label>
                                            </div>
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" name="options" id="optionsRadios2" value="3">Both
                                            </div>
                                        <div class="form-group">
                                            <label>Aim of the task-set</label>
                                            <textarea class="form-control" name="descp" rows="2" placeholder="Description of goals" autofocus required></textarea>
                                        </div>
                                           <div class="form-group">
                                            <label>Start date</label>
                                            <input class="form-control" name="s_date" type="date" autofocus required>
                                        </div>

                                        <div class="form-group">
                                            <label>End Date</label>
                                            <input class="form-control" name="e_date"type="date" autofocus required>
                                        </div>

                                        </div>
                                        <pre>
        <button type="submit" class="btn btn-success">Submit button</button>           <button type="reset" class="btn btn-danger">Reset Button</button>
                                        </pre>

                                    </form>
                                </div>
                                <!-- /.col-lg-6 (nested) -->

                                    </form>

                                </div>
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
   <div class="color-border"></div>

<!--footer ---------------------------------------------->
    <div class="footer">
                <div class="container">
                        <div class="infooter">
                        <p class="copyright">SOURCE CODE</p>
                        </div>
                <ul class="socialmedia">
                        <li><a href="https://www.github.com/sara-02/IWH-15"><i class="icon-github"></i></a></li>
                    </ul>
                    </div>
            </div>

    <!-- jQuery -->
    <script src="../bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>



</body>

</html>
